// $Id: scanner.h 17 2007-08-19 18:51:39Z tb $

#ifndef MLANG_SCANNER_H
#define MLANG_SCANNER_H



#ifndef __FLEX_LEXER_H
#define yyFlexLexer MLangFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

# include <map>
# include "mlang_parser.hh"

namespace yy {

/** Scanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to ExampleFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the Scanner class. This is required
 * because the yylex() defined in ExampleFlexLexer has no parameters. */
class Scanner : public MLangFlexLexer
{
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    Scanner(std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~Scanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual mlang_parser::token_type lex(
    		mlang_parser::semantic_type* yylval,
			mlang_parser::location_type* yylloc
	);

    /*
    virtual int LexerInput( char* buf, int max_size );
    */
    mlang_parser::token_type token_for(const std::string lexeme);

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);
    void begin_block();
    void end_block();
private:
    std::string m_block_content;
    std::map<std::string, mlang_parser::token_type> keywords;
};

} // namespace example

#endif // EXAMPLE_SCANNER_H
